### ISSUE TITLE
macOS binary broken

### ISSUE THREAD

**Issue by OfficialCRUGG** [ninstar/Rich-Presence-U#16] opened 2022-07-02 09:14 UTC
Hey there,
so I just bought this software for 5$ just to find out the macOS binary simply doesn't work... I'm on macOS Monterey 12.3.1 with an M1 processor

![image](https://user-images.githubusercontent.com/25248999/176994324-aeaadade-8058-470c-90e1-40d96c951ae4.png)

**Comment by OfficialCRUGG** [comment] 2022-07-02 09:18
Update: I was able to get it working by running `xattr -cr Rich\ Presence\ U.app` in the terminal. For the time being, you might want to mention this somewhere. Potentially in a readme inside the zip.

For the issue itself: I believe this is due to the file being zipped. This could be circumvented by creating a DMG Installer (view the image below for reference on what a DMG installer is)
![image](https://user-images.githubusercontent.com/25248999/176994461-9d69e4a0-da32-4e0c-a2f8-3c15b03a0b61.png)

**Comment by ninstar** [comment] 2022-07-03 09:02
I made it clear in the release note here and on itch.io that the macOS port was still considered experimental, I wasn't able to test it myself. The full report would be helpful, but I can't promise that I can patch it anytime soon, as I'm unable to use my computer at the moment.

**Comment by ninstar** [comment] 2022-07-04 16:42
I was talking to a friend about this, and I believe the problem is that you are using an ARM64 processor, everything has been tested on x86-64 processors, as I am not familiar with Apple hardware I was not aware of them using that architecture for their Mac processors.

**Comment by ninstar** [comment] 2022-07-05 15:47
It does support ARM64, but the RPC integration uses [this gdnative module](https://github.com/Abdera7mane/Godot-UnixSocket) to work on unix systems, which is running with x86-64, I would recompile it for macOS but at the moment I'm unable to do that.

**Comment by macbofh** [comment] 2022-07-12 23:12
It looks like the ARM code of one of the libraries has some bugs. You can run this application with the option "Open using Rosetta". You can find this option by right-clicking on the Application in the Finder and selection the option "Get Info"

<img width="377" alt="Rosetta" src="https://user-images.githubusercontent.com/1550491/178613773-fa54ab04-2eeb-4899-839d-66a3c3367ffa.png">

**Comment by OfficialCRUGG** [comment] 2022-07-12 23:19
That does indeed work. So the `xattr` command I posted above to fix the .app in combination with the "Open using Rosetta" check is a functional workaround to make Rich Presence U fully work on M1 processors.

**Comment by ninstar** [comment] 2022-09-04 16:14
Upstream added support for ARM64 Macs, closing this for now.

**Closed by ninstar** 2022-09-04 16:14 UTC
